//next
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

//styles
import styles from "./response.module.scss";

//components
import Layout from "../../components/layout/layout";

//questions
import questions from "../../questions/quest";

export default function res() {
  const router = useRouter();
  const { response } = router.query;
  const id = response;
  const [loading, setloading] = useState(true);
  const resp = questions.filter((quest) => quest.id == id);

  setTimeout(() => {
    setloading(false);
  }, 1000);
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || faq </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>F.A.Q ?</h1>
            </div>
          </div>
        </div>
        <div style={{ display: "flex", marginTop: "40px" }}>
          <div className={styles.categorie}>
            <ul>
              <a href="/faquestion">
                <li>Informations générales</li>
              </a>
              <a href="/faquestion">
                {" "}
                <li>Trajets & Paiements</li>
              </a>
            </ul>
          </div>
          <div className={styles.responseContainer}>
            <h2>{loading ? null : resp[0].ques}</h2>
            {loading ? null : resp[0].res.map((r) => <p>{r}</p>)}
            <a href={`${loading ? null : resp[0].links}`}>
              {loading ? null : resp[0].links}
            </a>
          </div>
        </div>
      </Layout>
    </div>
  );
}
