//next
import Head from "next/head";
import Image from "next/image";

//styles
import styles from "../styles/apropos.module.scss";

//components
import Layout from "../components/layout/layout";

//react-icons
import { AiOutlineRight } from "react-icons/ai";

export default function Apropos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || A propos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>À PROPOS</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna
              </p>
            </div>
            <div className={styles.page}>
              <p>Home</p>
              <AiOutlineRight className={styles.icon}></AiOutlineRight>
              <p>À propos</p>
            </div>
          </div>
        </div>

        <div className={styles.mission}>
          <h1 className={styles.title}>Qui sommes-nous ?</h1>
          <p>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout. The point
            of using Lorem Ipsum is that it has a more-or-less normal
            distribution of letters, as opposed to using 'Content here, content
            here', making it look like readable English. Many desktop publishing
            packages and web page editors now use Lorem Ipsum as their default
            model text, and a search for 'lorem ipsum' will uncover many web
            sites still in their infancy. Various versions have evolved over the
            years, sometimes by accident, sometimes on purpose injected humour
            and the like
          </p>
        </div>
        <div className={styles.mission}>
          <h1 className={styles.title}>D’où vient l’idée POGO ?</h1>
          <p>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout. The point
            of using Lorem Ipsum is that it has a more-or-less normal
            distribution of letters, as opposed to using 'Content here, content
            here', making it look like readable English. Many desktop publishing
            packages and web page editors now use Lorem Ipsum as their default
            model text, and a search for 'lorem ipsum' will uncover many web
            sites still in their infancy. Various versions have evolved over the
            years, sometimes by accident, sometimes on purpose injected humour
            and the like
          </p>
        </div>
        <div className={styles.mission}>
          <h1 className={styles.title}>Notre mission</h1>
          <p>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout. The point
            of using Lorem Ipsum is that it has a more-or-less normal
            distribution of letters, as opposed to using 'Content here, content
            here', making it look like readable English. Many desktop publishing
            packages and web page editors now use Lorem Ipsum as their default
            model text, and a search for 'lorem ipsum' will uncover many web
            sites still in their infancy. Various versions have evolved over the
            years, sometimes by accident, sometimes on purpose injected humour
            and the like
          </p>
        </div>

        <div className={styles.infoContainer}>
          <div className={styles.info}>
            <div
              className={styles.img}
              style={{ backgroundImage: "url(/bg.jpg)" }}
            >
              <div className={styles.filter}>
                <h1>INTEGRITY</h1>
              </div>
            </div>
            <div className={styles.description}>
              <div className={styles.filter}>
                <span>01</span>
                <div></div>
                <p>
                  Our diverse workforce is committed to delivering a safe,
                  sustainable micro-mobility experience in every city we serve.
                </p>
              </div>
            </div>
          </div>
          <div className={styles.info1}>
            <div
              className={styles.img}
              style={{ backgroundImage: "url(/bg1.jpg)" }}
            >
              <div className={styles.filter}>
                <h1>COMMUNITY</h1>
              </div>
            </div>
            <div className={styles.description}>
              <div className={styles.filter}>
                <span>02</span>
                <div></div>
                <p>
                  We hire locally and partner with neighborhood organizations to
                  cultivate community growth and improve urban living
                </p>
              </div>
            </div>
          </div>
          <div className={styles.info}>
            <div
              className={styles.img}
              style={{ backgroundImage: "url(/bg2.jpg)" }}
            >
              <div className={styles.filter}>
                <h1>TECHNOLOGY</h1>
              </div>
            </div>
            <div className={styles.description}>
              <div className={styles.filter}>
                <span>03</span>
                <div></div>
                <p>
                  Our drive to lead micro-mobility into the future puts Lime on
                  the cutting edge of clean, accessible urban transportation.
                </p>
              </div>
            </div>
          </div>
          <div className={styles.info1}>
            <div
              className={styles.img}
              style={{ backgroundImage: "url(/bg4.jpg)" }}
            >
              <div className={styles.filter}>
                <h1>TRUST</h1>
              </div>
            </div>
            <div className={styles.description}>
              <div className={styles.filter}>
                <span>04</span>
                <div></div>
                <p>
                  We believe in transparency and accountability, and strive to
                  deliver the best customer experience every day.
                </p>
              </div>
            </div>
          </div>
        </div>
        <p style={{ fontSize: "30px", textAlign: "center" }}>
          {" "}
          Various versions have evolved over the years, sometimes by accident,
          sometimes on purpose injected humour and the like
        </p>
      </Layout>
    </div>
  );
}
