//next
import Head from "next/head";

//styles
import styles from "../styles/comment.module.scss";

//components
import Layout from "../components/layout/layout";
import How from "../components/how/how";

//react-icons
import { AiOutlineRight } from "react-icons/ai";
import App from "../components/app/app";

export default function Comment() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || Comment ça Marche </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>Comment ça marche</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna
              </p>
            </div>
            <div className={styles.page}>
              <p>Home</p>
              <AiOutlineRight className={styles.icon}></AiOutlineRight>
              <p>Comment ça marche</p>
            </div>
          </div>
        </div>
        <How></How>
        <App></App>
      </Layout>
    </div>
  );
}
