//next
import Head from "next/head";
import Image from "next/image";

//styles
import styles from "../styles/apropos.module.scss";

//components
import Layout from "../components/layout/layout";

//react-icons
import { AiOutlineRight } from "react-icons/ai";
import { FaWhatsappSquare } from "react-icons/fa";
import { MdEmail, MdOutlineLocationCity } from "react-icons/md";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || Contactez-nous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>CONTACTEZ-NOUS</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna
              </p>
            </div>
            {/* <div className={styles.page}>
              <p>Home</p>
              <AiOutlineRight className={styles.icon}></AiOutlineRight>
              <p>Contactez-nous</p>
            </div> */}
          </div>
        </div>
        <div className={styles.contactContainer}>
          <div className={styles.desciption}></div>
        </div>
        <div className={styles.contactContainer}>
          <div className={styles.description}>
            <h3>Contactez-nous</h3>
            <p>
              {" "}
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna Lorem ipsum
              dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna
            </p>
            <div className={styles.infoContainer}>
              <div className={styles.info}></div>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
