//next
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

//styles
import styles from "../styles/faq.module.scss";

//components
import Layout from "../components/layout/layout";

//questions
import questions from "../questions/quest";

export default function faq() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || FAQ ? </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>Une question avant de monter en selle ?</h1>
            </div>
            {/* <div className={styles.page}>
              <p>Home</p>
              <AiOutlineRight className={styles.icon}></AiOutlineRight>
              <p>Contactez-nous</p>
            </div> */}
          </div>
        </div>
        <div className={styles.faqContainer}>
          {questions.map((question) => (
            <a
              onClick={() => router.push(`faq/${question.id}`)}
              key={question.id}
            >
              <div className={styles.question}>
                <p>{question.question}</p>
                <img src="/next.png" width="30px"></img>
              </div>
            </a>
          ))}
        </div>
      </Layout>
    </div>
  );
}
