//next
import Head from "next/head";
import { useState } from "react";

//styles
import styles from "../styles/faq.module.scss";

//components
import Layout from "../components/layout/layout";

//questions
import questions from "../questions/quest";

export default function faq() {
  const [categorie, setCategorie] = useState("informations generales");
  const [question, setquestion] = useState(
    questions.filter(
      (question) => question.categorie == "informations generales"
    )
  );
  const [toggle, setToggle] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || FAQ ? </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>Une question avant de monter en selle ?</h1>
            </div>
          </div>
        </div>
        <div className={styles.faqContainer}>
          <div className={styles.categorie}>
            <ul>
              <li
                className={
                  categorie == "informations generales" ? styles.selected : null
                }
                onClick={() => {
                  setCategorie("informations generales");
                  setquestion(
                    questions.filter(
                      (question) =>
                        question.categorie == "informations generales"
                    )
                  );
                }}
              >
                Informations générales
              </li>

              <li
                className={categorie == "paiement" ? styles.selected : null}
                onClick={() => {
                  setCategorie("paiement");
                  setquestion(
                    questions.filter(
                      (question) => question.categorie == "paiement"
                    )
                  );
                }}
              >
                Trajets et Paiements
              </li>
            </ul>
          </div>
          <div
            className={styles.categorieMobile}
            style={toggle ? null : { display: "none" }}
          >
            <ul>
              <li
                className={
                  categorie == "informations generales" ? styles.selected : null
                }
                onClick={() => {
                  setCategorie("informations generales");
                  setquestion(
                    questions.filter(
                      (question) =>
                        question.categorie == "informations generales"
                    )
                  );
                  setToggle(!toggle);
                }}
              >
                Informations générales
              </li>

              <li
                className={categorie == "paiement" ? styles.selected : null}
                onClick={() => {
                  setCategorie("paiement");
                  setquestion(
                    questions.filter(
                      (question) => question.categorie == "paiement"
                    )
                  );
                  setToggle(!toggle);
                }}
              >
                Trajets et Paiements
              </li>
            </ul>
          </div>
          <div className={styles.question}>
            <h3 onClick={() => setToggle(!toggle)}>Toutes les catégories</h3>
            <h2 className={styles.title}>{categorie}</h2>
            {question.map((question) => (
              <a href={`/faq/${question.id}`} key={question.id}>
                <p>{question.ques}</p>
                <img src="/next.png" width="30px"></img>
              </a>
            ))}
          </div>
        </div>
      </Layout>
    </div>
  );
}
