//next
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

//styles
import styles from "../styles/Home.module.scss";

//components
import Layout from "../components/layout/layout";
import Download from "../components/donwload/download";
import Info from "../components/info/info";
import Partenaire from "../components/marquee/marquee";

//react-icons
import { AiOutlineArrowDown } from "react-icons/ai";
import { BsFillPhoneFill, BsDot } from "react-icons/bs";
import Dynamic from "../components/dynamicAbout/dynamic";
import Scooter from "../components/scooter/scooter";
import Map from "../components/map/map";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.heroContainer}>
          <div className={styles.heroText}>
            <div className={styles.text}>
              <h1>
                <p>
                  Avec
                  <span>
                    <img
                      src="/pogo.png"
                      width="125px"
                      height="35px"
                      style={{ marginBottom: "-5px" }}
                    ></img>
                  </span>
                  , la location d’un véhicule électrique n’a jamais été aussi
                  simple !
                </p>
              </h1>
              <div className={styles.description}>
                {" "}
                <p>
                  Téléchargez notre application <span>POGO </span>et profitez de
                  la conduite de nos scooters modernes et écologiques dès
                  aujourd’hui !
                </p>
              </div>
              <Download style={{ marginTop: "20px" }}></Download>
            </div>
          </div>
          <div className={styles.mockup}>
            <img src="/mockup.png"></img>
          </div>
        </div>

        <div className={styles.scrollContainer}>
          <h3> Embrace </h3>
          <h3>The Revolution</h3>
        </div>

        <Info></Info>
        <div className={styles.inter}>
          <p>
            Ça donne vraiment envie ! Hein ? Vous deviendrez addictes à
            l’expérience POGO !{" "}
          </p>
        </div>
        <p
          id={"notre_flotte"}
          style={{ marginBottom: "200px", width: "200px" }}
        ></p>
        <h1 className={styles.title} id={"notre_flotte"}>
          Notre flotte
        </h1>
        {/* <h2 className={styles.sousTitle}>
          Formule <span> POGO </span>: 0 émission + 0 bruit + 0 odeur =
          <span> 100% fun</span>{" "}
        </h2> */}
        <Dynamic></Dynamic>

        <Dynamic reverse></Dynamic>
        <Map></Map>
        <p id={"comment"} style={{ marginBottom: "100px", width: "200px" }}></p>
        <h1 className={styles.title} id={"comment"}>
          Louez un scooter n’a jamais été aussi simple !{" "}
        </h1>
        <Scooter></Scooter>

        <p id={"combien"}></p>
        <h1 className={styles.title}>Combien ça coûte ?</h1>
        <h2 className={styles.sousTitle}>
          <div>
            <img src="/abonnement.png" width="35px" height="35px"></img>{" "}
            <p>Pas d’abonnement</p>
          </div>
          <div>
            <img src="/engagement.png" width="35px" height="35px"></img>{" "}
            <p>Pas d’engagement</p>
          </div>{" "}
          <div>
            <img src="/minute.png" width="35px" height="35px"></img>{" "}
            <p>Paiement à la minute </p>
          </div>
        </h2>
        <div className={styles.description}>
          <div className={styles.des}>
            {/* <div className={styles.type}>
              <BsDot className={styles.icon}></BsDot>
              <span>Nos tarifs</span>
            </div> */}
            <h3>POGO Packs</h3>
            <p>
              POGO propose à sa communauté des packs pour recharger son solde,
              avec des bonus très avantageux allant jusqu’à 50DH.
            </p>
            <p>
              POGO met la sécurité de sa communauté en tête de sa liste des
              priorités, c’est pour cela que chaque utilisateur de nos services
              est 100% assuré.
            </p>
            <a href="/tarif"> En savoir plus sur nos packs </a>
          </div>
          <div className={styles.tarif}>
            <h2>POGO Prix Basique </h2>
            <img src="basic.png" width="150px"></img>
            <p className={styles.price}>0.89 DH / min </p>
            <span style={{ fontWeight: "700" }}>0.19 DH / min de pause</span>
            <p>
              {" "}
              Vos locations sont facturées par prélèvement bancaire selon la
              somme due.{" "}
            </p>
            <div className={styles.checkContainer}>
              <div className={styles.check}>
                <img src="/check.png" width="25px" height="25px"></img>
                <span>
                  Payez vos minutes consommées à la fin de votre trajet{" "}
                </span>
              </div>
              <div className={styles.check}>
                <img src="/check.png" width="25px" height="25px"></img>
                <span>Protection 100% du conducteur et du passager</span>
              </div>
              <div className={styles.check}>
                <img src="/check.png" width="25px" height="25px"></img>
                <span>Assurance Responsabilité Civile </span>
              </div>
            </div>
          </div>
        </div>
        <h1 className={styles.title}>Nos partenaires</h1>
        <Partenaire></Partenaire>
      </Layout>
    </div>
  );
}
