//next
import Head from "next/head";
import Image from "next/image";

//styles
import styles from "../styles/termes.module.scss";

//components
import Layout from "../components/layout/layout";

//questions
import questions from "../questions/quest";

export default function Termes() {
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || Termes et conditions </title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>Les Conditions Générales d’Utilisation du Service POGO </h1>
            </div>
          </div>
        </div>
        <div className={styles.textContainer}>
          <div>
            <p>
              Les Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation &laquo;
              CGU &raquo; ci-pr&eacute;sentes d&eacute;finissent, &agrave;
              compter de leur acceptation par le Client, les conditions
              d&rsquo;acc&egrave;s et d&rsquo;utilisation du Service POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>
              POGO est un service de mobilit&eacute; &eacute;lectrique qui
              consiste en la location courte dur&eacute;e de v&eacute;hicules
              &eacute;lectriques (scooters et trottinettes) en libre-service. Il
              est propos&eacute; par la Soci&eacute;t&eacute; A
              Responsabilit&eacute; Limit&eacute;e, immatricul&eacute;e &agrave;
              F&egrave;s sous le num&eacute;ro 002783488000066, dont le
              si&egrave;ge social se situe &agrave; 209 B Lot Riad Laymoune Rte
              Mekn&egrave;s, Mag 3.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>ARTICLE 1 &ndash; D&Eacute;FINITIONS </strong>
            </p>
          </div>
          <div>
            <p>
              &laquo; Utilisateur &raquo; d&eacute;signe tout client,
              remplissant l&rsquo;ensemble des conditions &eacute;nonc&eacute;es
              &agrave; l&rsquo;article 4 des pr&eacute;sentes, ayant
              cr&eacute;&eacute; un compte POGO et finalis&eacute; son
              Inscription lui permettant d&rsquo;utiliser et de
              b&eacute;n&eacute;ficier du Service POGO dans les conditions des
              pr&eacute;sentes CGU.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation
              &raquo; ou &laquo; CGU &raquo; d&eacute;signe le pr&eacute;sent
              document dont les termes doivent avoir &eacute;t&eacute;
              accept&eacute;s par l&rsquo;Utilisateur pour pouvoir
              acc&eacute;der au Service.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Service &raquo; d&eacute;signe le service de location de
              courte dur&eacute;e de v&eacute;hicules en libre-service
              propos&eacute; par la soci&eacute;t&eacute; POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Location &raquo; d&eacute;signe le temps
              d&rsquo;utilisation du V&eacute;hicule par un Utilisateur. La
              Location d&eacute;marre d&egrave;s le d&eacute;blocage du
              V&eacute;hicule et se termine &agrave; l&rsquo;initiative de
              l&rsquo;Utilisateur (via l&rsquo;Application).&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; R&eacute;servation &raquo; d&eacute;signe l&rsquo;action
              de r&eacute;server un V&eacute;hicule via l&rsquo;Application
              avant la Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Application &raquo; d&eacute;signe l&rsquo;application
              mobile de POGO qui permet &agrave; l&rsquo;Utilisateur
              d&rsquo;acc&eacute;der au Service POGO, de r&eacute;server un
              V&eacute;hicule et commencer sa Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Site Internet &raquo; d&eacute;signe le site web du
              Service POGO disponible &agrave; l&rsquo;adresse{" "}
              <a
                href="http://www.pogo.ma/"
                rel="noreferrer noopener"
                target="_blank"
              >
                www.pogo.ma
              </a>
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Inscription &raquo; d&eacute;signe le processus
              d&rsquo;enregistrement d&rsquo;un futur Utilisateur au Service
              POGO. L&rsquo;inscription est gratuite.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Espace Personnel &raquo; d&eacute;signe l&rsquo;espace de
              gestion en ligne accessible par l&rsquo;Utilisateur ayant un
              compte POGO, accessible sur l&rsquo;Application POGO. En y
              acc&eacute;dant, l&rsquo;Utilisateur peut g&eacute;rer ses
              informations personnelles, de consulter son historique de
              Locations et ses factures POGO, ou d&rsquo;acheter des
              Packages.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Identifiants &raquo; d&eacute;signe l&rsquo;adresse email
              (ou le num&eacute;ro de t&eacute;l&eacute;phone portable) de
              l&rsquo;Utilisateur et le mot de passe qu&rsquo;il aura choisi
              pour s&rsquo;identifier et se connecter &agrave;
              l&rsquo;Application POGO et utiliser le Service.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; V&eacute;hicule &raquo; d&eacute;signe l&rsquo;un des
              scooters ou trottinettes &eacute;lectriques que POGO met &agrave;
              la disposition des Utilisateurs.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Scooter &raquo; d&eacute;signe l&rsquo;un des scooters
              &eacute;lectriques que POGO met &agrave; la disposition des
              Utilisateurs.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Trottinette &raquo; d&eacute;signe l&rsquo;une des
              trottinettes &eacute;lectriques que POGO met &agrave; la
              disposition des Utilisateurs.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Accessoires de l&rsquo;Utilisateur &raquo; d&eacute;signe
              les objets et effets personnels de l&rsquo;Utilisateur et des
              personnes transport&eacute;es dans le V&eacute;hicule au cours
              d&rsquo;une Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Casque &raquo; d&eacute;signe le casque appartenant
              &agrave; POGO, attach&eacute; au Scooter. Mis &agrave; la
              disposition de l&rsquo;Utilisateur afin qu&rsquo;il conduise le
              Scooter en toute s&eacute;curit&eacute;. &nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Documents de Bord &raquo; d&eacute;signe l&rsquo;ensemble
              des documents suivants : la copie du certificat d&rsquo;assurance,
              la copie du certificat de propri&eacute;t&eacute;, le constat
              amiable d&rsquo;accident, qui sont pr&eacute;sents &agrave; bord
              du V&eacute;hicule.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Pause &raquo; d&eacute;signe l&rsquo;arr&ecirc;t
              temporaire du V&eacute;hicule pendant une Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              &laquo; Service Client &raquo; d&eacute;signe le centre
              d&rsquo;information et d&rsquo;assistance de POGO qui
              r&eacute;pond aux r&eacute;clamations et aux questions des
              Utilisateurs. &nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong> ARTICLE 2 &ndash; OBJET </strong>
            </p>
          </div>
          <div>
            <p>
              Les pr&eacute;sentes CGU sont destin&eacute;es aux Utilisateurs du
              Service&nbsp;POGO&nbsp;sur le
              territoire&nbsp;marocain.&nbsp;Chaque Utilisateur&nbsp;souhaitant
              acc&eacute;der au Service&nbsp;est invit&eacute;&nbsp;&agrave;
              consulter&nbsp;et accepter&nbsp;les
              CGU&nbsp;pr&eacute;sentes&nbsp;sur l&rsquo;Application ainsi
              que&nbsp;sur&nbsp;le Site Internet 
              <a
                href="http://www.pogo.ma/"
                rel="noreferrer noopener"
                target="_blank"
              >
                www.pogo.ma
              </a>
              . Les CGU r&eacute;gissent l&rsquo;utilisation du Service et de
              l&rsquo;Application POGO que l&rsquo;Utilisateur se doit de
              respecter.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>
                ARTICLE 3 &ndash; MODALITES/TARIFS EN VIGUEUR DU SERVICE POGO{" "}
              </strong>
            </p>
          </div>
          <div>
            <div>
              <p>
                Le Service est factur&eacute; &agrave; la minute/minute de
                pause. &nbsp;
              </p>
            </div>
            <div>
              <p>Les tarifs applicables sont les suivants : &nbsp;</p>
            </div>
            <div>
              <ul>
                <li>
                  <p>0.99 DH la minute.&nbsp;</p>
                </li>
                <li>
                  <p>0.19 DH la minute de pause&nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                Toute Location et tout achat de &laquo; Package &raquo; est
                factur&eacute;.&nbsp;
              </p>
            </div>
          </div>
          <div>
            <p>
              Les &laquo; Packages &raquo; ont une dur&eacute;e de
              validit&eacute; telle qu&rsquo;elle est indiqu&eacute;e au moment
              de l&rsquo;achat sur l&rsquo;Application ou le Site Internet.
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              L&rsquo;achat de &laquo; Package &raquo; n&rsquo;est pas
              remboursable, sauf dans les conditions autorisant &agrave;
              l&rsquo;Utilisateur d&rsquo;exercer son droit de
              r&eacute;tractation (voir l&rsquo;article 6).&nbsp;
            </p>
          </div>
          <div>
            <p>
              Les prix et les p&eacute;nalit&eacute;s applicables &agrave;
              l&rsquo;utilisation du Service sont ceux en vigueur au jour de la
              R&eacute;servation. POGO se r&eacute;serve le droit de les
              modifier &agrave; tout moment conform&eacute;ment &agrave;
              l&rsquo;article xxxxxx des pr&eacute;sentes CGU.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>
                ARTICLE 4 &ndash; CONDITIONS D&rsquo;ACCES AU SERVICE{" "}
              </strong>
            </p>
          </div>
          <div>
            <p>
              Pour acc&eacute;der au Service POGO, l&rsquo;Utilisateur
              doit :&nbsp;
            </p>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>
                    &Ecirc;tre &acirc;g&eacute; d&rsquo;au moins 18 ans&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Disposer d&rsquo;un smartphone o&ugrave; est
                    t&eacute;l&eacute;charg&eacute;e la derni&egrave;re version
                    de l&rsquo;Application POGO.&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    T&eacute;l&eacute;transmettre &agrave; l&rsquo;aide de
                    l&rsquo;outil int&eacute;gr&eacute; dans l&rsquo;Application
                    les informations relatives &agrave; une ou plusieurs cartes
                    bancaires Visa ou Mastercard en cours de
                    validit&eacute;.&nbsp;
                  </p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                <strong>
                   ARTICLE 5 &ndash; MODALIT&Eacute;S D&rsquo;INSCRIPTION {" "}
                </strong>
              </p>
            </div>
            <div>
              <p>
                <strong>5.1 Inscription</strong> &nbsp;
              </p>
            </div>
          </div>
          <div>
            <div>
              <p>
                Pour s&rsquo;inscrire et devenir un Utilisateur POGO, le Client
                doit imp&eacute;rativement :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>
                    Remplir le formulaire d&rsquo;Inscription dans
                    l&rsquo;Application, dans lequel l&rsquo;Utilisateur
                    indique les informations suivantes :&nbsp;
                  </p>
                </li>
              </ul>
            </div>
            <div>
              <ul>
                <li>
                  <p>Son nom&nbsp;</p>
                </li>
                <li>
                  <p>Son pr&eacute;nom&nbsp;</p>
                </li>
                <li>
                  <p>Sa date de naissance&nbsp;</p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Une adresse e-mail valide&nbsp;</p>
                </li>
                <li>
                  <p>
                    Un num&eacute;ro de t&eacute;l&eacute;phone portable
                    valide&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Un mot de passe respectant les pr&eacute;conisations de
                    s&eacute;curit&eacute; de POGO&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Avoir consult&eacute; et accept&eacute; les pr&eacute;sentes
                    CGU ainsi que la Politique de Confidentialit&eacute; de POGO
                    accessibles sur l&rsquo;Application et sur le Site
                    Internet www.pogo.ma&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Les informations relatives &agrave; une ou plusieurs de ses
                    cartes bancaires Visa ou Mastercard en cours de
                    validit&eacute; sur l&rsquo;interface de paiement
                    s&eacute;curis&eacute;e pour le paiement des factures
                    ult&eacute;rieures&nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <p>
              Les informations communiqu&eacute;es doivent &ecirc;tre exactes et
              pr&eacute;cises.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>5.2 Prise d&rsquo;effet  </strong>
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Inscription de l&rsquo;Utilisateur prend effet directement
              &agrave; la fin du processus d&rsquo;Inscription d&eacute;crit
              ci-dessus. L&rsquo;Utilisateur peut donc b&eacute;n&eacute;ficier
              des services propos&eacute;s par POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>5.3 Dur&eacute;e  </strong>
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Inscription est sans limite de dur&eacute;e tant que
              l&rsquo;Utilisateur respecte l&rsquo;ensemble des CGU.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>5.4 D&eacute;sinscription  </strong>
            </p>
          </div>
          <div>
            <p>
              Le Service POGO est un service sans engagement,
              l&rsquo;Utilisateur peut &agrave; tout moment annuler son
              inscription en faisant une demande au Service Client par e-mail
              sur l&rsquo;adresse : <strong>info@pogo.ma</strong>&nbsp;
            </p>
          </div>
          <div>
            <p>
              Pour se d&eacute;sinscrire, l&rsquo;Utilisateur doit &ecirc;tre
              acquitt&eacute; de toutes les sommes qu&rsquo;il doit &agrave;
              POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Le solde de l&rsquo;Utilisateur sera perdu d&eacute;finitivement
              et ne lui sera en aucun cas rembours&eacute;.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>ARTICLE 6 &ndash; DROIT DE R&Eacute;TRACTATION  </strong>
            </p>
          </div>
          <div>
            <p>
              En tant que consommateur, le Client b&eacute;n&eacute;ficie
              d&rsquo;un droit de r&eacute;tractation conform&eacute;ment aux
              dispositions de la loi 31-08 &eacute;dictant des mesures de
              protection du consommateur.&nbsp;
            </p>
          </div>
          <div>
            <p>
              En acceptant les pr&eacute;sentes CGU, l&rsquo;Utilisateur consent
              que le contrat entre lui et POGO devient effectif d&egrave;s la
              confirmation de sa premi&egrave;re R&eacute;servation, et renonce
              express&eacute;ment &agrave; son droit de r&eacute;traction,
              conform&eacute;ment aux dispositions des articles de la loi 31-08
              &eacute;dictant des mesures de protection du consommateur.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Lorsqu&rsquo;il s&rsquo;agit d&rsquo;achat de
              &laquo; Package &raquo;, l&rsquo;Utilisateur peut exercer son
              droit de r&eacute;tractation dans un d&eacute;lai de sept (7)
              jours &agrave; compter de la date de l&rsquo;achat. Dans ce cas,
              l&rsquo;Utilisateur remplit et envoie le formulaire de
              r&eacute;tractation disponible ici au Service Client avant
              l&rsquo;expiration du d&eacute;lai susvis&eacute; &agrave;
              l&rsquo;adresse info@pogo.ma&nbsp;
            </p>
          </div>
          <div>
            <p>
              Si l&rsquo;Utilisateur exerce son droit de r&eacute;tractation
              sans avoir commenc&eacute; l&rsquo;utilisation du Service,
              l&rsquo;Utilisateur est int&eacute;gralement rembours&eacute; du
              montant du &laquo; Package &raquo; pay&eacute;.&nbsp;
            </p>
          </div>
          <div>
            <p>
               
              <strong>
                ARTICLE 7 &ndash; MODALIT&Eacute;S D&rsquo;UTILISATION DU
                SERVICE POGO{" "}
              </strong>
            </p>
          </div>
          <div>
            <div>
              <p>
                Le Service POGO n&rsquo;est accessible que via
                l&rsquo;Application. L&rsquo;Utilisateur se doit de prendre
                toutes les mesures et les pr&eacute;cautions n&eacute;cessaires
                pour assurer l&rsquo;acc&egrave;s &agrave; l&rsquo;Application
                via son smartphone disponible sur Android et iOS.&nbsp;
              </p>
            </div>
            <div>
              <p>
                <strong>7.1 Espace Personnel  </strong>
              </p>
            </div>
            <div>
              <p>Sur l&rsquo;Application, l&rsquo;Utilisateur peut :&nbsp;</p>
            </div>
            <div>
              <ul>
                <li>
                  <p>Contacter le Service Client &nbsp;</p>
                </li>
                <li>
                  <p>Consulter les FAQ (Frequently Asked Questions)&nbsp;</p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Consulter les CGU&nbsp;</p>
                </li>
                <li>
                  <p>
                    Mettre &agrave; jour ses donn&eacute;es personnelles
                    (adresse, mot de passe, cartes bancaires)&nbsp;
                  </p>
                </li>
                <li>
                  <p>Modifier sa ville de pr&eacute;f&eacute;rence&nbsp;</p>
                </li>
                <li>
                  <p>
                    Consulter son historique de R&eacute;servations et de
                    Locations&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Consulter et t&eacute;l&eacute;charger ses factures&nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>
                    Consulter son solde et acheter des
                    &laquo; Packages &raquo;&nbsp;
                  </p>
                </li>
                <li>
                  <p>Saisir un Code promotionnel&nbsp;</p>
                </li>
                <li>
                  <p>Modifier et partager son Code de parrainage&nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>&nbsp;</p>
            </div>
            <div>
              <p>
                <strong>7.2 Service Client </strong>
              </p>
            </div>
          </div>
          <div>
            <p>
              Les Utilisateurs peuvent contacter le Service Client comme
              suit :&nbsp;
            </p>
          </div>
          <div>
            <p>
              Par t&eacute;l&eacute;phone au +212 695 423 240, notamment en cas
              de probl&egrave;me, de dysfonctionnement du Service ou pour
              signaler un incident technique.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Par e-mail &agrave; l&rsquo;adresse info@pogo.ma pour poser des
              questions &agrave; propos de son compte POGO, signaler un
              probl&egrave;me technique rencontr&eacute; sur le V&eacute;hicule
              &eacute;lectrique ou sur l&rsquo;Application POGO, ou plus
              g&eacute;n&eacute;ralement apporter un commentaire.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>
                7.3 Informations sur les V&eacute;hicules et la
                R&eacute;servation
              </strong>
              &nbsp;
            </p>
          </div>
          <div>
            <p>Sur l&rsquo;Application, l&rsquo;Utilisateur peut :&nbsp;</p>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>
                    Visualiser le positionnement et l&rsquo;autonomie des
                    V&eacute;hicules disponibles dans les Parkings POGO&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Proc&eacute;der &agrave; la R&eacute;servation d&rsquo;un
                    Scooter&nbsp;
                  </p>
                </li>
                <li>
                  <p>Annuler sa R&eacute;servation&nbsp;</p>
                </li>
                <li>
                  <p>
                    Restituer un V&eacute;hicule lou&eacute; selon les termes
                    pr&eacute;vus par les pr&eacute;sentes CGU&nbsp;
                  </p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                <strong>7.4 Location d&rsquo;un V&eacute;hicule </strong>
              </p>
            </div>
          </div>
          <div>
            <p>
              <strong>
                7.4.1 R&eacute;servation d&rsquo;un V&eacute;hicule{" "}
              </strong>
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur choisit un V&eacute;hicule disponible, puis le
              r&eacute;serve via l&rsquo;Application. Il dispose alors de 15
              minutes pour se rendre au V&eacute;hicule r&eacute;serv&eacute; et
              le d&eacute;verrouiller en scannant gr&acirc;ce &agrave;
              l&rsquo;Application le code figurant sur le V&eacute;hicule.
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              Le scan du code du V&eacute;hicule marque la fin de la
              p&eacute;riode de R&eacute;servation du et le d&eacute;marrage de
              la p&eacute;riode de Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>
                7.4.2 &Eacute;tat des lieux &agrave; la prise du V&eacute;hicule{" "}
              </strong>
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur s&rsquo;engage &agrave; signaler au Service
              Client tout d&eacute;g&acirc;t qu&rsquo;il aura observ&eacute; sur
              le V&eacute;hicule avant son d&eacute;part, via la rubrique
              d&eacute;di&eacute;e de l&rsquo;Application ou par
              t&eacute;l&eacute;phone. L&rsquo;Utilisateur s&rsquo;engage, dans
              la mesure du possible, &agrave; prendre des photos des
              d&eacute;g&acirc;ts constat&eacute;s et les transmettre par
              l&rsquo;interm&eacute;diaire du formulaire de Contact dans
              l&rsquo;Application.&nbsp;
            </p>
          </div>
          <div>
            <div>
              <p>
                Liste non exhaustive des d&eacute;g&acirc;ts que
                l&rsquo;Utilisateur doit signaler au Service Client :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>Car&eacute;nages cass&eacute;s&nbsp;</p>
                </li>
                <li>
                  <p>Pneu crev&eacute;&nbsp;</p>
                </li>
                <li>
                  <p>R&eacute;troviseur manquant&nbsp;</p>
                </li>
                <li>
                  <p>Phare cass&eacute; &nbsp;</p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>B&eacute;quille cass&eacute;e&nbsp;</p>
                </li>
                <li>
                  <p>Levier de frein cass&eacute; ou tordu&nbsp;</p>
                </li>
                <li>
                  <p>Freins d&eacute;faillants &nbsp;</p>
                </li>
                <li>
                  <p>Lumi&egrave;res ne fonctionnant pas correctement&nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                Dans de telles circonstances, l&rsquo;Utilisateur s&rsquo;engage
                &agrave; ne pas utiliser le V&eacute;hicule
                endommag&eacute;.&nbsp;
              </p>
            </div>
          </div>
          <div>
            <div>
              <p>
                <strong>7.4.3 D&eacute;marrage du V&eacute;hicule </strong>
              </p>
            </div>
            <div>
              <p>
                Pour d&eacute;marrer le Scooter, l&rsquo;Utilisateur
                doit :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>
                    Sur l&rsquo;Application, appuyer sur &lsquo;&rsquo; Louer
                    &lsquo;&rsquo;&nbsp;
                  </p>
                </li>
                <li>
                  <p>Prendre le Casque attach&eacute; au Scooter&nbsp;</p>
                </li>
                <li>
                  <p>
                    Ajuster le Casque &agrave; sa taille et
                    l&rsquo;enfiler&nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Ajuster les r&eacute;troviseurs&nbsp;</p>
                </li>
                <li>
                  <p>Commencer son trajet&nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                <strong>7.4.4 Proc&eacute;dure de pause </strong>
              </p>
            </div>
            <div>
              <p>
                Pour stationner temporairement le Scooter, l&rsquo;Utilisateur
                doit :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>
                    B&eacute;quiller le Scooter sur un emplacement
                    autoris&eacute;&nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Attacher le Casque au crochet&nbsp;</p>
                </li>
                <li>
                  <p>
                    Retirer tous Accessoires de l&rsquo;Utilisateur du Scooter,
                    POGO ne pouvant en aucun cas &ecirc;tre tenue responsable de
                    tout objet oubli&eacute; ou vol&eacute;.&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Sur l&rsquo;Application, appuyer sur &lsquo;&rsquo; P mode
                    &lsquo;&rsquo;&nbsp;
                  </p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                Pendant la p&eacute;riode de Pause, chaque minute est
                factur&eacute;e selon le prix indiqu&eacute; dans
                l&rsquo;article 3.&nbsp;
              </p>
            </div>
            <div>
              <p>
                <strong>
                  7.4.6 Proc&eacute;dure de restitution du Scooter et de fin de
                  Location{" "}
                </strong>
              </p>
            </div>
          </div>
          <div>
            <div>
              <p>
                Pour restituer le Scooter et mettre fin &agrave; sa Location,
                l&rsquo;Utilisateur doit :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>
                    S&rsquo;assurer d&rsquo;&ecirc;tre dans un Parking POGO
                    (indiqu&eacute; sur l&rsquo;Application).&nbsp;
                  </p>
                </li>
                <li>
                  <p>B&eacute;quiller le Scooter.&nbsp;</p>
                </li>
                <li>
                  <p>
                    Restituer le Casque en l&rsquo;accrochant au Scooter&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Retirer tous les Accessoires de l&rsquo;Utilisateur du
                    Scooter, POGO ne pouvant en aucun cas &ecirc;tre tenue
                    responsable de tout objet oubli&eacute; ou
                    vol&eacute;.&nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>
                    Sur l&rsquo;Application, appuyer sur &lsquo;&rsquo; Fin
                    &lsquo;&rsquo; &nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Prendre une photo du Scooter &agrave; travers
                    l&rsquo;Application&nbsp;
                  </p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                L&rsquo;Utilisateur est responsable du contr&ocirc;le que la fin
                de sa Location est effective. Si le Scooter a &eacute;t&eacute;
                restitu&eacute; d&rsquo;une mani&egrave;re incorrecte, POGO ne
                pourra pas &ecirc;tre tenue responsable d&rsquo;une facturation
                prolong&eacute;e.&nbsp;
              </p>
            </div>
            <div>
              <p>
                <strong>
                  7.4.7 Fin de Location d&eacute;clench&eacute;e par POGO{" "}
                </strong>
              </p>
            </div>
            <div>
              <p>
                POGO se r&eacute;serve le droit de suspendre
                l&rsquo;acc&egrave;s au Service sans pr&eacute;avis,
                d&rsquo;annuler une R&eacute;servation ou de mettre fin &agrave;
                une Location dans les cas suivants, et ce sans qu&rsquo;aucune
                indemnit&eacute; ne soit due &agrave; l&rsquo;Utilisateur
                :&nbsp;
              </p>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>
                    Probl&egrave;me technique ou incident de
                    s&eacute;curit&eacute; affectant l&rsquo;utilisation du
                    Service ou la gestion des V&eacute;hicules.&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Fermeture du Service sur la d&eacute;cision d&rsquo;une
                    autorit&eacute; comp&eacute;tente ou pour toute raison
                    propre &agrave; POGO.&nbsp;
                  </p>
                </li>
                <li>
                  <p>Force majeure.&nbsp;</p>
                </li>
                <li>
                  <p>
                    Panne ou accident du V&eacute;hicule concern&eacute;.&nbsp;
                  </p>
                </li>
                <li>
                  <p>
                    Suspension ou d&eacute;sactivation du compte de
                    l&rsquo;Utilisateur ou de son acc&egrave;s au Service &nbsp;
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Vol du V&eacute;hicule pendant une Location.&nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                 &nbsp;
                <br />
                <strong>7.5 Proc&eacute;dure d&rsquo;assistance </strong>
              </p>
            </div>
            <div>
              <p>
                En cas d&rsquo;accident mat&eacute;riel et/ou corporel, de
                panne, ou de crevaison, l&rsquo;Utilisateur doit obligatoirement
                d&eacute;clencher la proc&eacute;dure d&rsquo;assistance en
                appelant le Service Client POGO au num&eacute;ro suivant
                +212 695 423 240, (co&ucirc;t d&rsquo;un appel local depuis un
                t&eacute;l&eacute;phone portable marocain)&nbsp;
              </p>
            </div>
            <div>
              <p>
                <strong>ARTICLE 8 &ndash; PAIEMENTS</strong>&nbsp;
              </p>
            </div>
            <div>
              <p>
                <strong>&nbsp;8.1 Dispositions g&eacute;n&eacute;rales </strong>
              </p>
            </div>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur s&rsquo;engage &agrave; s&rsquo;acquitter de
              toutes les sommes dont il serait redevable dans le cadre de
              l&rsquo;utilisation du Service POGO, notamment :&nbsp;
            </p>
          </div>
          <div>
            <p>Le prix d&rsquo;utilisation du Service POGO.&nbsp;</p>
          </div>
          <div>
            <p>
              Les contraventions dues aux &eacute;ventuelles infractions au Code
              de la route que l&rsquo;Utilisateur aura commises.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Les p&eacute;nalit&eacute;s &eacute;num&eacute;r&eacute;es
              &agrave; l&rsquo;article 10 des pr&eacute;sentes CGU.&nbsp;
            </p>
          </div>
          <div>
            <p>
             La franchise en cas d&rsquo;accident sans tiers responsable.&nbsp;
            </p>
          </div>
 <div>
            <p>
            L&rsquo;Utilisateur s&rsquo;engage &agrave; être à jour de ses obligations financi&egrave;res à
l&rsquo;&eacute;gard de POGO pendant toute la dur&eacute;e de la relation contractuelle.
            </p>
          </div>
<div><p>Les éléments dus par l&rsquo;Utilisateur identifiés ci-dessus feront l&rsquo;objet
d&rsquo;une facturation complémentaire, qui sera adressée à l&rsquo;Utilisateur
dans les trois (3) mois suivant la date de prise de connaissance par
POGO des faits donnant lieu à leur exigibilité.&nbsp;</p></div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>8.2 Paiement de la Location</strong>&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              Le prix de la Location, d&eacute;fini conform&eacute;ment &agrave;
              l&rsquo;article 3 est exigible &agrave; la fin de chaque
              Location.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              POGO &eacute;met une facture apr&egrave;s que l&rsquo;Utilisateur
              aie effectu&eacute; une ou plusieurs Locations. Le
              pr&eacute;l&egrave;vement sera effectu&eacute; soit depuis son
              solde POGO ou depuis la carte bancaire de l&rsquo;Utilisateur
              (selon le mode qu&rsquo;il a choisi) dont les coordonn&eacute;es
              ont &eacute;t&eacute; saisies au moment de l&rsquo;Inscription,
              dans l&rsquo;intervalle de temps indiqu&eacute; sur la
              facture.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              En cas de rejet du pr&eacute;l&egrave;vement, l&rsquo;Utilisateur
              peut r&eacute;gler sa facture directement &agrave; POGO depuis son
              Espace Personnel. La r&eacute;gularisation d&rsquo;un incident de
              paiement par paiement direct permettra le d&eacute;blocage de
              l&rsquo;acc&egrave;s au Service de l&rsquo;Utilisateur, sauf si le
              blocage r&eacute;sulte &eacute;galement du non-respect
              d&rsquo;autres stipulations des pr&eacute;sentes CGU.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>8.3 Mise &agrave; jour des moyens de paiement </strong>
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur doit mettre &agrave; jour ses
              coordonn&eacute;es et informations bancaires au fur et &agrave;
              mesure de leurs &eacute;ventuels changements, afin que les
              informations &agrave; disposition de POGO soient &agrave; jour
              pendant toute la dur&eacute;e de la relation contractuelle.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              Dans le cas o&ugrave; la carte bancaire de l&rsquo;Utilisateur
              s&rsquo;expirera, il doit absolument mettre &agrave; jour ses
              coordonn&eacute;es bancaires quinze (15) jours avant
              l&rsquo;expiration de sa carte.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              En cas d&rsquo;invalidit&eacute; de la carte bancaire de
              l&rsquo;Utilisateur pour une raison quelconque, POGO pourra
              suspendre l&rsquo;acc&egrave;s au Service jusqu&rsquo;&agrave; ce
              que la situation soit r&eacute;gularis&eacute;e.l&rsquo;Utilisateur reste
néanmoins redevable des échéances de ses factures impayées.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>
                &nbsp;8.4 Autorisation de pr&eacute;l&egrave;vement sur la carte
                bancaire
              </strong>
              &nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              En saisissant ses r&eacute;f&eacute;rences de carte bancaire lors
              de son Inscription ou dans le cadre de toute mise &agrave; jour de
              ses informations bancaires dans son Espace Personnel, et en
              acceptant les pr&eacute;sentes CGU, l&rsquo;Utilisateur consent
              &agrave; POGO une autorisation de pr&eacute;l&egrave;vement sur
              carte bancaire pour tous montants dus par l&rsquo;Utilisateur
              notamment :&nbsp;
            </p>
          </div>
          <div>
            <div>
              <ul>
                <li>
                  <p>Les frais de Location.&nbsp;</p>
                </li>
                <li>
                  <p>Les p&eacute;nalit&eacute;s.&nbsp;</p>
                </li>
                <li>
                  <p>La franchise en cas d&rsquo;accident ou de vol sans tiers
responsable.&nbsp;</p>
                </li>
              </ul>
            </div>
<div > <p> Une empreinte de la carte bancaire de l&rsquo;Utilisateur est
indispensable pour valider l&rsquo;Inscription et autoriser le prélèvement
des montants dus.&nbsp; </p></div>
            <div>
              <p>
                <strong>8.5 Facturation </strong>
              </p>
            </div>
            <div>
              <p>&nbsp;</p>
            </div>
          </div>
          <div>
            <div>
              <p>
                L&rsquo;Utilisateur s&rsquo;engage &agrave; payer les frais de
                Location correspondants. Ces frais de Location incluent le
                montant &eacute;quivalent du nombre de minutes de location ainsi
                que le montant pour chaque minute de Pause. &nbsp;
              </p>
            </div>
            <div>
              <p>
                Les frais appliqu&eacute;s sont conformes &agrave; ceux
                indiqu&eacute;s sur l&rsquo;Application POGO ainsi que dans
                l&rsquo;article 3 des CGU ci-pr&eacute;sentes.&nbsp;
              </p>
            </div>
            <div>
              <p>
                Les frais de Location sont dus d&egrave;s la fin du contrat de
                Location.&nbsp;
              </p>
            </div>
            
            
          </div>
          <div>
            
            <div>
              <p>
                Pour tout remboursement, POGO utilise toujours le m&ecirc;me
                mode de paiement que celui utilis&eacute; par
                l&rsquo;Utilisateur pour la transaction initiale.&nbsp;
              </p>
            </div>
            <div>
              <p>
                En acceptant les pr&eacute;sentes CGU, l&rsquo;Utilisateur
                d&eacute;clare que lui et lui seul dispose du droit l&eacute;gal
                d&rsquo;utiliser le mode de paiement pr&eacute;vu et
                d&rsquo;autoriser les transactions. Dans le cas o&ugrave; POGO
                soup&ccedil;onne que les informations concernant le mode de
                paiement qui ont &eacute;t&eacute; transmises par
                l&rsquo;Utilisateur sont frauduleuses, POGO se r&eacute;serve le
                droit de bloquer compl&egrave;tement l&rsquo;acc&egrave;s au
                compte ainsi qu&rsquo;aux Service POGO sans notification
                pr&eacute;alable, l&rsquo;Utilisateur devra se justifier et
                clarifier la situation au Support de POGO afin de
                d&eacute;bloquer son compte et reprendre l&rsquo;utilisation du
                Service.&nbsp;
              </p>
            </div>
            <div>
              <p>
                Il est de la responsabilit&eacute; de l&rsquo;Utilisateur de
                veiller &agrave; ce que ses fonds soient suffisant pour faire
                une Location. Que ce soit le solde sur son compte POGO (issu de
                l&rsquo;achat de Package), ou les fonds sur sa carte
                bancaire.&nbsp;
              </p>
            </div>
            <div>
              <p>&nbsp;</p>
            </div>
          </div>
<div><p><strong>ARTICLE 9 &ndash; PROTECTION DES DONNEES PERSONNELLES DE L&rsquo;UTILISATEUR </strong> &nbsp;</p></div>

<div><p>Les destinataires des données personnelles concernant un Utilisateur, à l&rsquo;exception des données
bancaires confidentielles, et qui sont transmises par POGO à la plateforme sécurisée de paiement en
ligne Stripe, pourront être en vertu de l&rsquo;autorisation de la Commission Nationale de Contrôle de la
Protection des Données à Caractère Personnel «CNDP, les collaborateurs de Stripe, responsables du
traitement dont la finalité est le suivi de l&rsquo;opération du paiement initiée par le payeur sur le site
marchand.</p>
<p>
  Les données recueillies par Stripe ne peuvent être utilisées à des fins de prospection par ce dernier et
sont la propriété du marchand qui a délégué la gestion du paiement à Stripe.
  </p>
<p>L&rsquo;Utilisateur peut accéder à ses données personnelles traitées par Stripe et qui figurent sur le reçu de
la facture à l&rsquo;exception des données bancaires en téléchargeant ses factures depuis l&rsquo;Application
POGO, ou en contactant le support POGO.</p>
<p>L&rsquo;achat d&rsquo;un Pack POGO ou le paiement effectué à la fin de chaque location vaut une acceptation
irrévocable des présentes conditions générales d&rsquo;utilisation du service de Stripe. Pour toute demande
de rectification de vos données personnelles, ou d&rsquo;annulation de la demande de paiement, vous
devez vous adresser au support POGO.</p>
<p>L&rsquo;ensemble des données personnelles de chaque membre est conservé dans les meilleures
conditions de sécurité et de confidentialité auprès des services techniques de POGO.</p>
<p>Conformément aux dispositions du Dahir n 1-09-15 du 18 février 2009 portant promulgation de la loi
n 09-08 relative à la protection des personnes physiques à l&rsquo;égard du traitement des données à
caractère personnel et de son décret d&rsquo;application n 2-09-165 du 18 juin 2009, chaque Utilisateur
dispose d&rsquo;un droit d&rsquo;accès, de modification, de rectification et de suppression des données
personnelles le concernant. Pour exercer ce droit, l&rsquo;Utilisateur peut accéder directement à son
espace personnel sur l&rsquo;Application POGO « Compte » ou en contactant le support POGO par appel
téléphonique sur le numéro : +212 695 423 240 ou par mail sur l’adresse : info@pogo.ma</p>
<p>En acceptant les présentes Conditions Générales d&rsquo;Utilisation, l&rsquo;Utilisateur autorise POGO à lui
adresser par e-mail ou SMS des offres promotionnelles. Chaque Utilisateur peut à tout moment
mettre fin à la réception de ces offres promotionnelles en se désabonnant sur le mail ou en
désactivant les notifications via les paramètres.</p>
<p>Chaque Utilisateur reconnaît être informé et accepte que POGO conserve ses données personnelles
pendant la durée d’ouverture de son compte.</p>
</div>
          <div>
            <p>
              <strong>
                ARTICLE 10 &ndash; OBLIGATIONS DE L&rsquo;UTILISATEUR
              </strong>
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>
                &nbsp;10.1 Engagement de l&rsquo;Utilisateur par rapport au
                V&eacute;hicule POGO
              </strong>
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              Avant d&rsquo;entamer sa Location et commencer la conduite du
              V&eacute;hicule POGO, l&rsquo;Utilisateur doit s&rsquo;assurer que
              le V&eacute;hicule et ses accessoires sont dans un bon &eacute;tat
              et pr&ecirc;t &agrave; &ecirc;tre utilis&eacute; (pneus en bon
              &eacute;tat, r&eacute;troviseurs fonctionnels ..)&nbsp;
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur doit conduire le V&eacute;hicule en respectant
              les dispositions du Code la route et conform&eacute;ment aux CGU
              ci-pr&eacute;sentes. Tout en utilisant les &eacute;l&eacute;ments
              de s&eacute;curit&eacute; fournis.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Durant toute la dur&eacute;e du Location, l&rsquo;Utilisateur est
              responsable du V&eacute;hicule et doit le consid&eacute;rer comme
              sa propre propri&eacute;t&eacute;. Il doit donc le stationner dans
              les endroits autoris&eacute;s et s&rsquo;assurer qu&rsquo;il est
              en s&eacute;curit&eacute; (pr&eacute;sence de cam&eacute;ras de
              surveillance ou agent de s&eacute;curit&eacute;). &nbsp;
            </p>
          </div>
          <div>
            <div>
              <p>
                Une fois en circulation, il est interdit &agrave;
                l&rsquo;Utilisateur de manger, boire, fumer ou pratiquer toute
                activit&eacute; pouvant compromettre sa
                s&eacute;curit&eacute;.&nbsp;
              </p>
            </div>
            <div>
              <p>
                L&rsquo;Utilisateur doit respecter le nombre de passagers
                transport&eacute;s autoris&eacute;s pour chaque
                v&eacute;hicule :&nbsp;
              </p>
            </div>
            <div>
              <ul>
                <li>
                  <p>2 passagers pour les Scooters&nbsp;</p>
                </li>
                <li>
                  <p>1 passager pour les Trottinettes &nbsp;</p>
                </li>
              </ul>
            </div>
            <div>
              <p>
                L&rsquo;Utilisateur ne pourra utiliser le V&eacute;hicule ou
                permettre &agrave; quiconque de l&rsquo;utiliser pour une
                activit&eacute; &agrave; laquelle il n&rsquo;est pas
                con&ccedil;u ou &agrave; des fins illicites.&nbsp;
              </p>
            </div>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>
                &nbsp;10.2 Conducteur d&rsquo;un v&eacute;hicule POGO{" "}
              </strong>
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              Les V&eacute;hicules POGO ne doivent &ecirc;tre conduit que par
              l&rsquo;Utilisateur qui les a lou&eacute;s. L&rsquo;Utilisateur
              s&rsquo;engage &agrave; ne laisser aucune autre personne que
              lui-m&ecirc;me conduire le V&eacute;hicule, m&ecirc;me si cette
              derni&egrave;re est &eacute;galement un Utilisateur du Service
              POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>
              En cas de non-respect de cet engagement, l&rsquo;Utilisateur aura
              affaire &agrave; des p&eacute;nalit&eacute;s. &nbsp;
            </p>
          </div>
          <div>
            <p>
              Toute utilisation de l&rsquo;Application avec les Identifiants de
              l&rsquo;Utilisateur est consid&eacute;r&eacute;e avoir
              &eacute;t&eacute; faite par l&rsquo;Utilisateur lui-m&ecirc;me. Il
              est d&rsquo;ailleurs responsable de la cr&eacute;ation, de la
              conservation et de l&rsquo;utilisation de ses Identifiants, qui
              lui sont strictement personnels et ne doivent pas &ecirc;tre
              communiqu&eacute;s &agrave; d&rsquo;autres personnes. Il est de sa
              responsabilit&eacute; de pr&eacute;server leur
              confidentialit&eacute; et s&eacute;curit&eacute;. &nbsp;
            </p>
          </div>
          <div>
            <p>
              En cas de perte ou de vol de son mot de passe, l&rsquo;Utilisateur
              doit le modifier imm&eacute;diatement pour que son compte soit en
              s&eacute;curit&eacute;.&nbsp;
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur est enti&egrave;rement responsable de toute
              utilisation du Service via l&rsquo;Application install&eacute;e
              sur son smartphone. M&ecirc;me si cette utilisation a
              &eacute;t&eacute; faite par un tiers &agrave; son insu.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>10.3 Capacit&eacute; de conduite </strong>
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur s&rsquo;engage au moment de
              l&rsquo;utilisation d&rsquo;un V&eacute;hicule POGO &agrave; ne
              pas se trouver sous l&rsquo;emprise de l&rsquo;alcool, de la
              drogue, de m&eacute;dicaments ou toute autre substance
              alt&eacute;rant ses facult&eacute;s ou sa capacit&eacute; &agrave;
              ma&icirc;triser le V&eacute;hicule. &nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>10.4 Dommages </strong>
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur est seul et entier responsable des dommages
              aux personnes et aux biens (en ce compris au V&eacute;hicule)
              caus&eacute;s par l&rsquo;utilisation qui est faite du Scooter
              durant toute la dur&eacute;e de la Location.&nbsp;
            </p>
          </div>
          <div>
            <p>
              L&rsquo;Utilisateur est tenu de restituer le V&eacute;hicule dans
              le m&ecirc;me &eacute;tat que celui o&ugrave; il &eacute;tait
              avant la Location. En cas de perte ou de dommages survenus pendant
              la p&eacute;riode de Location, l&rsquo;Utilisateur devra
              indemniser POGO des pr&eacute;judices et frais encourus. Lors de
              la r&eacute;paration, le prix sera communiqu&eacute; &agrave;
              l&rsquo;Utilisateur et pr&eacute;lev&eacute; sur sa carte
              bancaire. &nbsp;
            </p>
          </div>
<table style={{width: "100%" , border-color: "#03D3B9",border:"2"}}>
<tbody>
<tr>
<th>Pi&egrave;ce</th>
<th>Tarif</th>
</tr>
<tr>
<td>R&eacute;troviseur</td>
<td>46 MAD</td>
</tr>
<tr>
<td>Car&eacute;nage du c&ocirc;t&eacute;</td>
<td>85 MAD</td>
</tr>
<tr>
<td>Garde-boue du devant</td>
<td>79 MAD</td>
</tr>
<tr>
<td>Car&eacute;nage avant</td>
<td>105 MAD</td>
</tr>
<tr>
<td>Repose-pieds</td>
<td>94 MAD</td>
</tr>
<tr>
<td>B&eacute;quille lat&eacute;rale</td>
<td>54 MAD</td>
</tr>
<tr>
<td>B&eacute;quille centrale</td>
<td>159 MAD</td>
</tr>
<tr>
<td>Barre lat&eacute;rale basse</td>
<td>57 MAD</td>
</tr>
<tr>
<td>Repose-pied</td>
<td>101 MAD</td>
</tr>
<tr>
<td>Topcase</td>
<td>300 MAD</td>
</tr>
</tbody>
</table>
<!-- DivTable.com -->
          <div>
            <p>
              En cas d&apos;insuffisance des fonds permettant d&eacute;duire ces
              frais, POGO pourra contacter l&rsquo;Utilisateur afin que ce
              dernier puisse effectuer le paiement de ces montants.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>ARTICLE 11 &ndash; PENALITES ET SANCTIONS : </strong>
            </p>
          </div>
          <div>
            <p>
              Des p&eacute;nalit&eacute;s seront appliqu&eacute;es &agrave;
              l&rsquo;Utilisateur en cas de non-respect des pr&eacute;sentes
              CGU : &nbsp;
            </p>
          </div>
          <div>
            <p>
              Abandon du V&eacute;hicule pendant la Location hors Parking POGO :
              &nbsp;
            </p>
          </div>
          <div>
            <p>
              La Location reste effective sans plafonnement de facturation
              jusqu&rsquo;&agrave; la restitution du V&eacute;hicule par
              l&rsquo;Utilisateur ou, si ce dernier refuse, jusqu&rsquo;&agrave;
              ce qu&rsquo;un agent ou un d&eacute;panneur mandat&eacute; par
              POGO le r&eacute;cup&egrave;re. L&rsquo;Utilisateur sera
              factur&eacute; des frais de la Location ainsi que du rapatriement
              du V&eacute;hicule au Parking POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>D&eacute;faut de Paiement :&nbsp;</p>
          </div>
          <div>
            <p>
              Non-paiement des sommes dues &agrave; POGO par
              l&rsquo;Utilisateur.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Sanction : Suspension de l&rsquo;acc&egrave;s au Service
              jusqu&rsquo;au paiement des sommes dues.&nbsp;
            </p>
          </div>
          <div>
            <p>
              Panne de batterie : due &agrave; la n&eacute;gligence de
              l&rsquo;Utilisateur et entrainant l&rsquo;intervention de POGO ou
              d&rsquo;un d&eacute;panneur mandat&eacute; par POGO.&nbsp;
            </p>
          </div>
          <div>
            <p>Perte ou d&eacute;gradation du Casque :&nbsp;</p>
          </div>
          <div>
            <p>
              Enl&egrave;vement du Scooter en fourri&egrave;re ou par les
              services de Police : due &agrave; un stationnement
              non-autoris&eacute;.&nbsp;
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>
              <strong>ARTICLE 12&ndash; ASSURANCES : </strong>
            </p>
          </div>
          <div>
            <p>
              En utilisant les services de POGO, l&rsquo;Utilisateur est
              assur&eacute;.&nbsp;
            </p>
          </div>
          <div>
            <p>
              <strong>12.1 Assurance Responsabilit&eacute; Civile&nbsp;</strong>
            </p>
          </div>
          <div>
            <p>
              <strong>12.2 Protection du conducteur&nbsp;</strong>
            </p>
          </div>
          <div>
            <p>
              <strong>
                12.3 Protection de la personne transport&eacute;e{" "}
              </strong>
            </p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
          <div>
            <p>&nbsp;</p>
          </div>
        </div>
      </Layout>
    </div>
  );
}
