//next
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";

//styles
import styles from "../styles/termes.module.scss";

//components
import Layout from "../components/layout/layout";

//questions
import questions from "../questions/quest";

export default function Termes() {
  const router = useRouter();
  const [categorie, setCategorie] = useState("informations generales");
  const [question, setquestion] = useState(
    questions.filter(
      (question) => question.categorie == "informations generales"
    )
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>POGO || FAQ ? </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      <Layout>
        <div className={styles.aboutContainer}>
          <div className={styles.filter}>
            <div className={styles.description}>
              <h1>Les Conditions Générales d’Utilisation du Service POGO </h1>
            </div>
          </div>
        </div>
        <div className={styles.textContainer}>
          <p>
            Les Conditions Générales d’Utilisation « CGU » ci-présentes
            définissent, à compter de leur acceptation par le Client, les
            conditions d’accès et d’utilisation du Service POGO. POGO est un
            service de mobilité électrique qui consiste en la location courte
            durée de véhicules électriques (scooters et trottinettes) en
            libre-service. Il est proposé par la Société A Responsabilité
            Limitée, immatriculée à Fès sous le numéro xxxxxxx, dont le siège se
            situe à xxxxxxxxxxx.
          </p>
          <h2>ARTICLE 1 – DÉFINITIONS </h2>
          <p>
            « Utilisateur » désigne tout client, remplissant l’ensemble des
            conditions énoncées à l’article 4 des présentes, ayant créé un
            compte POGO et finalisé son Inscription lui permettant d’utiliser et
            de bénéficier du Service POGO dans les conditions des présentes CGU.{" "}
          </p>
          <p>
            « Conditions Générales d’Utilisation » ou « CGU » désigne le présent
            document dont les termes doivent avoir été acceptés par
            l’Utilisateur pour pouvoir accéder au Service.{" "}
          </p>
          <p>
            « Service » désigne le service de location de courte durée de
            véhicules en libre-service proposé par la société POGO.{" "}
          </p>
          <p>
            « Location » désigne le temps d’utilisation du Véhicule par un
            Utilisateur. La Location démarre dès le déblocage du Véhicule et se
            termine à l’initiative de l’Utilisateur (via l’Application).{" "}
          </p>
          <p>
            « Réservation » désigne l’action de réserver un Véhicule via
            l’Application avant la Location.{" "}
          </p>
          <p>
            « Application » désigne l’application mobile de POGO qui permet à
            l’Utilisateur d’accéder aux Service POGO, de réserver un Véhicule et
            commencer sa Location.{" "}
          </p>
          <p>
            « Site Internet » désigne le site web du Service POGO disponible à
            l’adresse<span> www.pogo.ma</span>{" "}
          </p>
          <p>
            « Inscription » désigne le processus d’enregistrement d’un futur
            Utilisateur au Service POGO. L’inscription est gratuite.{" "}
          </p>
          <p>
            « Espace Personnel » désigne l’espace de gestion en ligne accessible
            par l’Utilisateur ayant un compte POGO, accessible sur le Site
            Internet www.pogo.ma ou depuis. En y accédant, l’Utilisateur peut
            gérer ses informations personnelles, de consulter son historique de
            Locations et ses factures POGO, ou d’acheter des Packs.{" "}
          </p>
          <p>
            « Identifiants » désigne l’adresse email (ou le numéro de téléphone
            portable) de l’Utilisateur et le mot de passe qu’il aura choisi pour
            s’identifier et se connecter à l’Application POGO et utiliser le
            Service.{" "}
          </p>
          <p>
            « Véhicule » désigne l’un des scooters ou trottinettes électriques
            que POGO met à la disposition des Utilisateurs.{" "}
          </p>
          <p>
            « Scooter » désigne l’un des scooters électriques que POGO met à la
            disposition des Utilisateurs.{" "}
          </p>
          <p>
            « Trottinette » désigne l’une des trottinettes électriques que POGO
            met à la disposition des Utilisateurs.{" "}
          </p>
          <p>
            « Accessoires de l’Utilisateur » désigne les objets et effets
            personnels de l’Utilisateur et des personnes transportées dans le
            Véhicule au cours d’une Location.{" "}
          </p>
          <p>
            « Casque » désigne le casque appartenant à POGO, attaché au Scooter.
            Mis à la disposition de l’Utilisateur afin qu’il conduise le Scooter
            en toute sécurité.{" "}
          </p>
          <p>
            « Documents de Bord » désigne l’ensemble des documents suivants : la
            copie du certificat d’assurance, la copie de la carte grise, le
            constat amiable d’accident, qui sont présents dans le Véhicule.{" "}
          </p>
          <p>
            « Pause » désigne l’arrêt temporaire du Scooter pendant une
            Location.{" "}
          </p>
          <p>
            « Service Client » désigne le centre d’information et d’assistance
            de POGO qui répond aux réclamations et aux questions des
            Utilisateurs.{" "}
          </p>
          <h2> ARTICLE 2 – OBJET </h2>
          <p>
            Les présentes CGU sont destinées aux Utilisateurs du Service POGO
            sur le territoire marocain. Chaque Utilisateur souhaitant accéder au
            Service est invité à consulter et accepter les CGU présentes sur
            l’Application ainsi que sur le Site Internet 
            <span>www.pogo.ma</span>. Les CGU régissent l’utilisation du Service
            et de l’Application POGO que l’Utilisateur se doit de respecter.{" "}
          </p>
          <h2>ARTICLE 3 – MODALITES/TARIFS EN VIGUEUR DU SERVICE POGO </h2>
          <p>Le Service est facturé à la minute/minute de pause. </p>
          <p>Les tarifs applicables sont les suivants  :</p>
          <ul>
            <li>
              <p>0.89 DH la minute. </p>
            </li>
            <li>
              <p>0.09 DH la minute de pause </p>
            </li>
          </ul>
          <p>Toute Location et tout achat de « Pack » est facturé. </p>
          <p>
            Les « Packs » ont une durée de validité telle qu’elle est indiquée
            au moment de l’achat sur l’Application ou le Site Internet.{" "}
          </p>
          <p>
            L’achat de « Pack » n’est pas remboursable, sauf dans les conditions
            autorisant à l’Utilisateur d’exercer son droit de rétractation (voir
            l’article 6).{" "}
          </p>
          <p>
            Les prix et les pénalités applicables à l’utilisation du Service
            sont ceux en vigueur au jour de la Réservation. POGO se réserve le
            droit de les modifier à tout moment conformément à l’article xxxxxx
            des présentes CGU.{" "}
          </p>
          <h2>ARTICLE 4 – CONDITIONS D’ACCES AU SERVICE </h2>
          <p>Pour accéder au Service POGO, l’Utilisateur doit : </p>
          <ul>
            <li>
              <p>Être âgé d’au moins 18 ans </p>
            </li>
            <li>
              <p>
                Disposer d’un smartphone où est téléchargée la dernière version
                de l’Application POGO.{" "}
              </p>
            </li>
            <li>
              <p>
                Télétransmettre à l’aide de l’outil intégré dans l’Application
                un scan d’un document d’identification officiel tel que :{" "}
              </p>
              <ul>
                <li>
                  <p>Carte d’identité </p>
                </li>
                <li>
                  <p>Passeport </p>
                </li>
                <li>
                  <p>Permis de conduire </p>
                </li>
              </ul>
            </li>
            <li>
              <p>
                Télétransmettre à l’aide de l’outil intégré dans l’Application
                les informations relatives à une ou plusieurs cartes bancaires
                Visa ou Mastercard en cours de validité.{" "}
              </p>
            </li>
          </ul>
          <h2> ARTICLE 5 – MODALITÉS D’INSCRIPTION  </h2>
          <h3>5.1 Inscription  </h3>
          <p>
            Pour s’inscrire et devenir un Utilisateur POGO, le Client doit
            impérativement :{" "}
          </p>
          <ul>
            <li>
              <p>
                Remplir le formulaire d’Inscription dans l’Application, dans
                lequel l’Utilisateur indique les informations suivantes :{" "}
              </p>
              <ul>
                <li>
                  <p>Son nom </p>
                </li>
                <li>
                  <p>Son prénom </p>{" "}
                </li>
                <li>
                  <p>Sa date de naissance</p>
                </li>
                <li>
                  <p>Une adresse e-mail valide </p>
                </li>
                <li>
                  <p>Un numéro de téléphone portable valide </p>
                </li>
                <li>
                  <p>
                    Un mot de passe respectant les préconisations de sécurité
                    de POGO{" "}
                  </p>
                </li>
                <li>
                  <p>
                    Avoir consulté et accepté les présentes CGU ainsi que la
                    Politique de Confidentialité de POGO accessibles sur
                    l’Application et sur le Site Internet
                    <span>  www.pogo.ma</span>{" "}
                  </p>
                </li>
                <li>
                  <p>
                    Les informations relatives à une ou plusieurs de ses cartes
                    bancaires Visa ou Mastercard en cours de validité sur
                    l’interface de paiement sécurisée pour le paiement des
                    factures ultérieures.{" "}
                  </p>
                </li>
              </ul>
            </li>
            <li>
              <p>
                Télétransmettre à l’aide de l’outil intégré dans l’Application
                un document d’identification officiel : Carte d’identité,
                passeport ou permis de conduire{" "}
              </p>
            </li>
          </ul>
          <p>
            Les informations communiquées doivent être exactes et précises.{" "}
          </p>
          <h3>5.2 Prise d’effet  </h3>
          <p>
            L’Inscription de l’Utilisateur prend effet à la fin du processus
            d’Inscription décrit ci-dessus, après la vérification des
            informations et des documents télétransmis par l’Utilisateur. POGO
            ne garantit aucun délai entre une demande d’Inscription et sa prise
            d’effet. {" "}
          </p>
          <h3>5.3 Durée  </h3>
          <p>
            L’Inscription est sans limite de durée tant que l’Utilisateur
            respecte l’ensemble des CGU.{" "}
          </p>
          <h3>5.4 Désinscription  </h3>
          <p>
            Le Service POGO est un service sans engagement, l’Utilisateur peut à
            tout moment annuler son inscription en faisant une demande au
            Service Client par e-mail sur l’adresse : xxxxxxxxxxxx{" "}
          </p>
          <p>
            Pour se désinscrire, l’Utilisateur doit être acquitté de toutes les
            sommes qu’il doit à POGO.{" "}
          </p>
          <p>
            Le solde de l’Utilisateur sera perdu définitivement et ne lui sera
            en aucun cas remboursé.{" "}
          </p>
          <h2>ARTICLE 6 – DROIT DE RÉTRACTATION  </h2>
          <p>
            En tant que consommateur, le Client bénéficie d’un droit de
            rétractation conformément aux dispositions de la loi 31-08 édictant
            des mesures de protection du consommateur. En acceptant les
            présentes CGU, l’Utilisateur consent que le contrat entre lui et
            POGO devient effectif dès la confirmation de sa première
            Réservation, et renonce expressément à son droit de rétraction,
            conformément aux dispositions des articles de la loi 31-08 édictant
            des mesures de protection du consommateur. Lorsqu’il s’agit d’achat
            de « Pack », l’Utilisateur peut exercer son droit de rétractation
            dans un délai de sept (7) jours à compter de la date de l’achat.
            Dans ce cas, l’Utilisateur remplit et envoie le formulaire de
            rétractation disponible{" "}
            <a href="#">
              <span>ici</span>
            </a>{" "}
            au Service Client avant l’expiration du délai susvisé à l’adresse
            xxxxxxxxxxxxxxxxxxxxxxxxx{" "}
          </p>
          <p>
            Si l’Utilisateur exerce son droit de rétractation sans avoir
            commencé l’utilisation du Service, l’Utilisateur est intégralement
            remboursé du montant du « Pack » payé.{" "}
          </p>
          <h2> ARTICLE 7 – MODALITÉS D’UTILISATION DU SERVICE POGO </h2>
          <p>
            Le Service POGO n’est accessible que via l’Application.
            L’Utilisateur se doit de prendre toutes les mesures et les
            précautions nécessaires pour assurer l’accès à l’Application via son
            smartphone disponible sur Android et iOS.{" "}
          </p>
          <h3>7.1 Espace Personnel  </h3>
          <p>
            Que ce soit sur l’Application ou sur<span> le Site Internet </span>,
            l’Utilisateur peut :{" "}
          </p>
          <ul>
            <li>
              <p>Contacter le Service Client </p>
            </li>
            <li>
              <p>Consulter les FAQ (Frequently Asked Questions) </p>
            </li>
            <li>
              <p>Consulter les CGU </p>
            </li>
            <li>
              <p>Consulter la Politique de Confidentialité </p>
            </li>
            <li>
              <p>
                Mettre à jour ses données personnelles (adresse, mot de passe,
                cartes bancaires){" "}
              </p>
            </li>
            <li>
              <p>Modifier sa ville de préférence </p>
            </li>
            <li>
              <p>Consulter son historique de Réservations et de Locations </p>
            </li>
            <li>
              <p>Consulter et télécharger ses factures </p>
            </li>
            <li>
              <p>
                Consulter son statut Utilisateur et les éventuels avantages
                acquis{" "}
              </p>
            </li>
            <li>
              <p>Consulter son solde et acheter des « Pack » </p>
            </li>
            <li>
              <p>Saisir un Code promotionnel </p>
            </li>
            <li>
              <p>Modifier et partager son Code de parrainage </p>
            </li>
          </ul>
          <h3>7.2 Service Client </h3>
          <p>
            Les Utilisateurs peuvent contacter le Service Client comme suit :{" "}
          </p>
          <p>
            Par téléphone au xxxxxxxxxx, disponible 24h/24 et
            7jours/7, notamment en cas de problème, de dysfonctionnement du
            Service ou pour signaler un incident technique.{" "}
          </p>
          <p>
            Par e-mail à l’adresse xxxxxxxxxxx pour poser des questions à propos
            de son compte POGO, signaler un problème technique rencontré sur le
            Véhicule électrique ou sur l’Application POGO, ou plus généralement
            apporter un commentaire.{" "}
          </p>
          <h3>7.3 Informations sur les Véhicules et la Réservation </h3>
          <p>Sur l’Application, l’Utilisateur peut : </p>
          <ul>
            <li>
              <p>
                Visualiser le positionnement et l’autonomie des Véhicules
                disponibles dans les Parkings POGO{" "}
              </p>
            </li>
            <li>
              <p>Procéder à la Réservation d’un Scooter </p>
            </li>
            <li>
              <p>Annuler sa Réservation </p>
            </li>
            <li>
              <p>
                Restituer un Véhicule loué selon les termes prévus par les
                présentes CGU{" "}
              </p>
            </li>
          </ul>
          <h3>7.4 Location d’un Véhicule </h3>
          <h3>7.4.1 Réservation d’un Véhicule </h3>
          <p>
            L’Utilisateur choisit un Véhicule disponible, puis le réserve via
            l’Application. Il dispose alors de 15 minutes pour se rendre au
            Véhicule réservé et le déverrouiller en scannant grâce à
            l’Application le code figurant sur le Véhicule.{" "}
          </p>
          <p>
            Le scan du code du Véhicule marque la fin de la période de
            Réservation du et le démarrage de la période de Location.{" "}
          </p>
          <p>
            Si l’Utilisateur n’a pas déverrouillé le Véhicule pendant la période
            de Réservation de 15 minutes, sa Réservation est automatiquement
            annulée. {" "}
          </p>
          <h3>7.4.2 Déverrouillage du Véhicule </h3>
          <p>
            Afin de déverrouiller le Véhicule qu’il a réservé, l’Utilisateur
            doit, grâce à l’Application, scanner le code figurant sur le
            Véhicule, et mettre le Véhicule en mode « ON ».{" "}
          </p>
          <h3>7.4.3 État des lieux à la prise du Véhicule </h3>
          <p>
            L’Utilisateur s’engage à signaler au Service Client tout dégât qu’il
            aura observé sur le Véhicule avant son départ, via la rubrique
            dédiée de l’Application ou par téléphone. L’Utilisateur s’engage,
            dans la mesure du possible, à prendre des photos des dégâts
            constatés et les transmettre par l’intermédiaire du formulaire de
            Contact dans l’Application.{" "}
          </p>
          <p>
            Liste non exhaustive des dégâts que l’Utilisateur doit signaler au
            Service Client :{" "}
          </p>
          <ul>
            <li>
              <p>Carénages cassés </p>
            </li>
            <li>
              <p>Pneu crevé </p>
            </li>
            <li>
              <p>Rétroviseur manquant </p>
            </li>
            <li>
              <p>Phare cassé </p>
            </li>
            <li>
              <p>Béquille cassée </p>
            </li>
            <li>
              <p>Levier de frein cassé ou tordu </p>
            </li>
            <li>
              <p>Freins défaillants </p>
            </li>
            <li>
              <p>Lumières ne fonctionnant pas correctement </p>
            </li>
          </ul>
          <p>
            Dans de telles circonstances, l’Utilisateur s’engage à ne pas
            utiliser le Véhicule endommagé.{" "}
          </p>
          <h3>7.4.4 Démarrage du Véhicule </h3>
          <p>
            Pour démarrer le Scooter après l’avoir déverrouillé, l’Utilisateur
            doit :{" "}
          </p>
          <ul>
            <li>
              <p>Prendre le Casque attaché au Scooter </p>
            </li>
            <li>
              <p>Ajuster le Casque à sa taille et l’enfiler </p>
            </li>
            <li>
              <p>Ajuster les rétroviseurs </p>
            </li>
            <li>
              <p>Mettre le Scooter en mode « ON » </p>
            </li>
          </ul>
          <p>
            Pour démarrer la Trottinette après l’avoir déverrouillée,
            l’Utilisateur doit :
          </p>
          <h3>7.4.5 Procédure de pause </h3>
          <p>
            Pour stationner temporairement le Scooter, l’Utilisateur doit :{" "}
          </p>
          <ul>
            <li>
              <p>Béquiller le Scooter sur un emplacement autorisé </p>
            </li>
            <li>
              <p>Attacher le Casque au crochet </p>
            </li>
            <li>
              <p>Attacher le Casque au crochet </p>
            </li>
            <li>
              <p>
                Retirer tous Accessoires de l’Utilisateur du Scooter, POGO ne
                pouvant en aucun cas être tenue responsable de tout objet oublié
                ou volé.{" "}
              </p>
            </li>
            <li>
              <p>Mettre le Scooter en mode « PAUSE ». </p>
            </li>
          </ul>
          <p>
            Pendant la période de Pause, chaque minute est facturée selon le
            prix indiqué dans <span>l’article 3.</span>{" "}
          </p>
          <h3>
            7.4.6 Procédure de restitution du Scooter et de fin de Location{" "}
          </h3>
          <p>
            Pour restituer le Scooter et mettre fin à sa Location, l’Utilisateur
            doit :{" "}
          </p>
          <ul>
            <li>
              <p>
                S’assurer d’être dans un Parking POGO (indiqué sur
                l’Application).{" "}
              </p>
            </li>
            <li>
              <p>Béquiller le Scooter. </p>
            </li>
            <li>
              <p>Restituer le Casque en l’accrochant au Scooter </p>
            </li>
            <li>
              <p>
                Retirer tous Accessoires de l’Utilisateur du Scooter, POGO ne
                pouvant en aucun cas être tenue responsable de tout objet oublié
                ou volé.{" "}
              </p>
            </li>
            <li>
              <p>Mettre le Scooter dans le mode « OFF ». </p>
            </li>
            <li>
              <p>
                Prendre le Scooter en 4 photos couvrant tous les angles via la
                rubrique dédiée de l’Application.{" "}
              </p>
            </li>
          </ul>
          <p>
            L’Utilisateur est responsable du contrôle que la fin de sa Location
            est effective. Si le Scooter a été restitué d’une manière
            incorrecte, POGO ne pourra pas être tenue responsable d’une
            facturation prolongée.{" "}
          </p>
          <h3>7.4.7 Fin de Location déclenchée par POGO </h3>
          <p>
            POGO se réserve le droit de suspendre l’accès au Service sans
            préavis, d’annuler une Réservation ou de mettre fin à une Location
            dans les cas suivants, et ce sans qu’aucune indemnité ne soit due à
            l’Utilisateur :{" "}
          </p>
          <ul>
            <li>
              <p>
                Problème technique ou incident de sécurité affectant
                l’utilisation du Service ou la gestion des Véhicules.{" "}
              </p>
            </li>
            <li>
              <p>
                Fermeture du Service sur la décision d’une autorité compétente
                ou pour toute raison propre à POGO.{" "}
              </p>
            </li>
            <li>
              <p>Force majeure. </p>
            </li>
            <li>
              <p>Panne ou accident du Véhicule concerné. </p>
            </li>
            <li>
              <p>
                Suspension ou désactivation du compte de l’Utilisateur ou de son
                accès au Service conformément à l’article xxxxxx des présentes
                CGU.{" "}
              </p>
            </li>
            <li>
              <p>Vol du Véhicule pendant une Location. </p>
            </li>
          </ul>
          <h3>7.5 Procédure d’assistance</h3>
          <p>
            En cas d’accident matériel et/ou corporel, de panne, ou de
            crevaison, l’Utilisateur doit obligatoirement déclencher la
            procédure d’assistance en appelant le Service Client POGO au numéro
            suivant xxxxxxxxx (coût d’un appel local depuis un téléphone
            portable marocain){" "}
          </p>
          <h2>ARTICLE 8 – PAIEMENTS </h2>
          <h3>8.1 Dispositions générales</h3>
          <p>
            L’Utilisateur s’engage à s’acquitter de toutes les sommes dont il
            serait redevable dans le cadre de l’utilisation du Service POGO,
            notamment :{" "}
          </p>
          <p>Le prix d’utilisation du Service POGO. </p>
          <p>
            Les contraventions dues aux éventuelles infractions au Code de la
            route que l’Utilisateur aura commises.{" "}
          </p>
          <p>Les pénalités énumérées à l’article 10 des présentes CGU. </p>
          <p>Les franchises d’assurance en cas d’accident. </p>
          <h3>8.2 Paiement de la Location </h3>
          <p>
            Le prix de la Location, défini conformément à l’article 3 est
            exigible à la fin de chaque Location.{" "}
          </p>
          <p>
            POGO émet une facture après que l’Utilisateur aie effectué une ou
            plusieurs Locations. Le prélèvement sera effectué soit depuis son
            solde POGO ou depuis la carte bancaire de l’Utilisateur (selon le
            mode qu’il a choisi) dont les coordonnées ont été saisies au moment
            de l’Inscription, dans l’intervalle de temps indiqué sur la facture.{" "}
          </p>
          <p>
            En cas de rejet du prélèvement, l’Utilisateur peut régler sa facture
            directement à POGO depuis son Espace Personnel. La régularisation
            d’un incident de paiement par paiement direct permettra le déblocage
            de l’accès au Service de l’Utilisateur, sauf si le blocage résulte
            également du non-respect d’autres stipulations des présentes CGU.{" "}
          </p>
          <h3>8.1 Mise à jour des moyens de paiement </h3>
          <p>
            L’Utilisateur doit mettre à jour ses coordonnées et informations
            bancaires au fur et à mesure de leurs éventuels changements, afin
            que les informations à disposition de POGO soient à jour pendant
            toute la durée de la relation contractuelle.{" "}
          </p>
          <p>
            Dans le cas où la carte bancaire de l’Utilisateur s’expirera, il
            doit absolument mettre à jour ses coordonnées bancaires quinze (15)
            jours avant l’expiration de sa carte.{" "}
          </p>
          <p>
            En cas d’invalidité de la carte bancaire de l’Utilisateur pour une
            raison quelconque, POGO pourra suspendre l’accès au Service jusqu’à
            ce que la situation soit régularisé.{" "}
          </p>
          <h3> 8.2 Autorisation de prélèvement sur la carte bancaire </h3>
          <p>
            En saisissant ses références de carte bancaire lors de son
            Inscription ou dans le cadre de toute mise à jour de ses
            informations bancaires dans son Espace Personnel, et en acceptant
            les présentes CGU, l’Utilisateur consent à POGO une autorisation de
            prélèvement sur carte bancaire pour tous montants dus par
            l’Utilisateur notamment :{" "}
          </p>
          <ul>
            <li>
              <p>Les frais de Location. </p>
            </li>
            <li>
              <p>Les pénalités. </p>
            </li>
            <li>
              <p>La franchise en cas d’accident ou de vol. </p>
            </li>
          </ul>
          <h3>8.3 Facturation </h3>
          <p>
            L’Utilisateur s’engage à payer les frais de Location correspondants.
            Ces frais de Location incluent le montant équivalent du nombre de
            kilomètres parcourus ainsi que le montant pour chaque minute de
            Pause.{" "}
          </p>
          <p>
            Les frais appliqués sont conformes à ceux indiqués sur l’Application
            POGO ainsi que dans l’article 3 des CGU ci-présentes.{" "}
          </p>
          <p>
            Les frais de Location sont dus dès la fin du contrat de Location.{" "}
          </p>
          <p>
            L’Utilisateur peut choisir parmi les modes de paiement affichés lors
            du processus de commande :{" "}
          </p>
          <ul>
            <li>
              <p>Payement par carte bancaire </p>
            </li>
            <li>
              <p>
                Payement par le solde sur son Compte POGO issu de l’achat d’un
                Pack{" "}
              </p>
            </li>
          </ul>
          <p>
            Pour tout remboursement, POGO utilise toujours le même mode de
            paiement que celui utilisé par l’Utilisateur pour la transaction
            initiale.{" "}
          </p>
          <p>
            En acceptant les présentes CGU, l’Utilisateur déclare que lui et lui
            seul dispose du droit légal d’utiliser le mode de paiement prévu et
            d’autoriser les transactions. Dans le cas où POGO soupçonne que les
            informations concernant le mode de paiement qui ont été transmises
            par l’Utilisateur sont frauduleuses, POGO se réserve le droit de
            bloquer complètement l’accès au compte ainsi qu’aux Service POGO
            sans notification préalable, l’Utilisateur devra se justifier et
            clarifier la situation au Support de POGO afin de débloquer son
            compte et reprendre l’utilisation du Service.{" "}
          </p>
          <p>
            Il est de la responsabilité de l’Utilisateur de veiller à ce que ses
            fonds soient suffisant pour faire une Location. Que ce soit le solde
            sur son compte POGO (issu de l’achat de Pack), ou les fonds sur sa
            carte bancaire.{" "}
          </p>
          <h2>ARTICLE 9 – OBLIGATIONS DE L’UTILISATEUR </h2>
          <h3>
            {" "}
            9.1 Engagement de l’Utilisateur par rapport au Véhicule POGO{" "}
          </h3>
          <p>
            Avant d’entamer sa Location et commencer la conduite du Véhicule
            POGO, l’Utilisateur doit s’assurer que le Véhicule et ses
            accessoires sont dans un bon état et prêt à être utilisé (pneus en
            bon état, rétroviseurs fonctionnels ..){" "}
          </p>
          <p>
            L’Utilisateur doit conduire le Véhicule en respectant les
            dispositions du Code la route et conformément aux CGU ci-présentes.
            Tout en utilisant les éléments de sécurité fournis. Durant toute la
            durée du Location, l’Utilisateur est responsable du Véhicule et doit
            le considérer comme sa propre propriété. Il doit donc le stationner
            dans les endroits autorisés et s’assurer qu’il est en sécurité
            (présence de caméras de surveillance ou agent de sécurité)
          </p>
          <p>
            Une fois en circulation, il est interdit à l’Utilisateur de manger,
            boire, fumer ou pratiquer toute activité pouvant compromettre sa
            sécurité.{" "}
          </p>
          <p>
            L’Utilisateur doit respecter le nombre de passagers transportés
            autorisés pour chaque véhicule :{" "}
          </p>
          <ul>
            <li>
              <p>2 passagers pour les Scooters </p>
            </li>
            <li>
              <p>1 passager pour les Trottinettes </p>
            </li>
            <li>
              <p>X passagers pour les Voitures</p>{" "}
            </li>
          </ul>
          <p>
            L’Utilisateur ne pourra utiliser le Véhicule ou permettre à
            quiconque de l’utiliser pour une activité à laquelle il n’est pas
            conçu ou à des fins illicites.{" "}
          </p>
          <h2> 9.3 Conducteur d’un véhicule POGO </h2>
          <p>
            Les Véhicules POGO ne doivent être conduit que par l’Utilisateur qui
            les a loués. L’Utilisateur s’engage à ne laisser aucune autre
            personne que lui-même conduire le Véhicule, même si cette dernière
            est également un Utilisateur du Service POGO. En cas de non-respect
            de cet engagement, l’Utilisateur aura affaire à des pénalités. Toute
            utilisation de l’Application avec les Identifiants de l’Utilisateur
            est considérée avoir été faite par l’Utilisateur lui-même. Il est
            d’ailleurs responsable de la création, de la conservation et de
            l’utilisation de ses Identifiants, qui lui sont strictement
            personnels et ne doivent pas être communiqués à d’autres personnes.
            Il est de sa responsabilité de préserver leur confidentialité et
            sécurité.{" "}
          </p>
          <p>
            En cas de perte ou de vol de son mot de passe, l’Utilisateur doit le
            modifier immédiatement pour que son compte soit en sécurité.{" "}
          </p>
          <p>
            L’Utilisateur est entièrement responsable de toute utilisation du
            Service via l’Application installée sur son smartphone. Même si
            cette utilisation a été faite par un tiers à son insu.{" "}
          </p>
          <h3>9.5 Capacité de conduite </h3>
          <p>
            L’Utilisateur s’engage au moment de l’utilisation d’un Véhicule POGO
            à ne pas se trouver sous l’emprise de l’alcool, de la drogue, de
            médicaments ou toute autre substance altérant ses facultés ou sa
            capacité à maîtriser le Véhicule.{" "}
          </p>
          <h3>9.7 Dommages </h3>
          <p>
            Des pénalités seront appliquées à l’Utilisateur en cas de
            non-respect des présentes CGU :{" "}
          </p>
          <p>
            <span>
              Abandon du Véhicule pendant la Location hors Parking POGO :
            </span>{" "}
          </p>
          <p>
            La Location reste effective sans plafonnement de facturation jusqu’à
            la restitution du Véhicule par l’Utilisateur ou, si ce dernier
            refuse, jusqu’à ce qu’un agent ou un dépanneur mandaté par POGO le
            récupère. L’Utilisateur sera facturé des frais de la Location ainsi
            que du rapatriement du Véhicule au Parking POGO.{" "}
          </p>
          <p>Pénalité : xxxxx DH </p>
          <p>
            <span>Défaut de Paiement : </span>
          </p>
          <p>Non-paiement des sommes dues à POGO par l’Utilisateur. </p>
          <p>
            Sanction : Suspension de l’accès au Service jusqu’au paiement des
            sommes dues.{" "}
          </p>
          <p>
            <span> Panne de batterie : </span> due à la négligence de
            l’Utilisateur et entrainant l’intervention de POGO ou d’un dépanneur
            mandaté par POGO.
          </p>
          <p>Pénalité : xxxxx DH </p>
          <p>
            <span>Perte ou dégradation du Casque : </span>
          </p>
          <p>Pénalité : 100 DH </p>
          <p>
            <span>
              Enlèvement du Scooter en fourrière ou par les services de Police :{" "}
            </span>
            due à un stationnement non-autorisé.
          </p>
          <p>Pénalité : xxxxx DH </p>
          <h2>ARTICLE 11– ASSURANCES : </h2>
          <h3>10.1 Assurance Responsabilité Civile </h3>
          <h3>10.2 Protection du conducteur </h3>
          <h3>10.3 Protection de la personne transportée</h3>
          <h3> 10.4 Vol 10.5 Incendie</h3>
          <h3>10.6 Bris de glace</h3>
        </div>
      </Layout>
    </div>
  );
}
